TEMP: Add debug statements in fetch_service test - Added `dbg!` statements to print the hashes of `sorted_exclude_fetch_mempool_tx` and `sorted_txids`
Apparently the failing `zcashd::get::mempool_tx` test fails because the variables being compared are in the same order (weird, it's comparing crossed entries, 1 vs 0 index of each).

Is the ordering wrong? the values do match on both variables tho... @oscar-pepper might know the about this.

Output:

```BASH
    tx.hash.clone()).collect::<Vec<_>>() = [
        [
            15,
            200,
            188,
            23,
            178,
            215,
            200,
            52,
            152,
            29,
            209,
            158,
            73,
            129,
            27,
            243,
            47,
            28,
            206,
            190,
            68,
            66,
            171,
            12,
            78,
            88,
            54,
            191,
            234,
            92,
            188,
            158,
        ],
        [
            78,
            202,
            230,
            106,
            102,
            125,
            54,
            109,
            0,
            212,
            148,
            79,
            127,
            219,
            132,
            55,
            22,
            174,
            208,
            8,
            99,
            12,
            104,
            59,
            185,
            179,
            60,
            15,
            163,
            170,
            216,
            172,
        ],
    ]
    [integration-tests/tests/fetch_service.rs:1665:5] &sorted_txids = [
        [
            15,
            200,
            188,
            23,
            178,
            215,
            200,
            52,
            152,
            29,
            209,
            158,
            73,
            129,
            27,
            243,
            47,
            28,
            206,
            190,
            68,
            66,
            171,
            12,
            78,
            88,
            54,
            191,
            234,
            92,
            188,
            158,
        ],
        [
            78,
            202,
            230,
            106,
            102,
            125,
            54,
            109,
            0,
            212,
            148,
            79,
            127,
            219,
            132,
            55,
            22,
            174,
            208,
            8,
            99,
            12,
            104,
            59,
            185,
            179,
            60,
            15,
            163,
            170,
            216,
            172,
        ],
    ]

    thread 'zcashd::get::mempool_tx' (138) panicked at integration-tests/tests/fetch_service.rs:1667:5:
    assertion `left == right` failed
      left: [15, 200, 188, 23, 178, 215, 200, 52, 152, 29, 209, 158, 73, 129, 27, 243, 47, 28, 206, 190, 68, 66, 171, 12, 78, 88, 54, 191, 234, 92, 188, 158]
     right: [78, 202, 230, 106, 102, 125, 54, 109, 0, 212, 148, 79, 127, 219, 132, 55, 22, 174, 208, 8, 99, 12, 104, 59, 185, 179, 60, 15, 163, 170, 216, 172]
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```