Break db and see what happens I purpously flip `TransactionHash`'s serde ordering to see how tests/compiler catch the blatant db constraint breach. So far I've found errors in db tests, which is good, but they aren't specific for the field I broke. This makes sense because i flipped it both for read and write to db, and only for v1 also. So the consecuences are, i belive:
- when reading an old entry, it's going to get in backward so it loads with garbage data
- that data, although garbage, is still a valid txhash so there's no way for the type to pick up on it being wrong
- thus, the real error can only happen when trying to use that value to compose a block, and that's the error we end up getting:

```BASH
    thread '<unnamed>' panicked at zaino-state/src/chain_index/tests/vectors.rs:92:43:
    called `Result::unwrap()` on an `Err` value: InvalidBlock { height: 102, hash: BlockHash(cbe1285df13b9c79f0843875ad8cfae5f13cdd0f3e62ce1cb8bb83ff06779e63), reason: "Invalid block data: invalid transparent input." }
```

So, conclusiong so far are:
- tests are catching this specific blatant break, not sure about more subtle ones
- it's not obvious from the tests error logs exactly what is failing (i know it's txhash because i changed it, has this been unadverted and i could have spent hours debugging this)

---
There's another concerning aspect i realised about during this work, that is the write_block funciton being a deep rat nest of complexity. we NEED to refactor it, it's unmantainable and unhackable as it stands.